### ISSUE TITLE
Nice setup, but it breaks the command-line vim unfortunately.

### ISSUE THREAD

**Issue by artsyca** [paulkoegel/vimrc-osx#1]
Sorry to say I'm not much of an expert in vim. However it looks like this vimrc setup only works in macvim; The command-line client becomes somewhat unusable due to strange screen behaviour. (in iTerm)

**Comment by paulkoegel** [comment]
yep, same problem here. sorry, never using the command line version, and haven't updated my vim plugins / vimrc in ages. best start with vanilla macvim and put in the bits you really neeed step by step. let me know if i can be of help.
